<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/ApplicationConnectorServiceLibrary/Siebel/V2/RequesterABCS/UpdateRCCDetailsSiebelReqABCSImpl.wsdl"/>
      <rootElement name="UpdateRCCDetailsRequest" namespace="http://www.telia.org/Siebel/getRCCBalances"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/ApplicationConnectorServiceLibrary/Siebel/V2/RequesterABCS/UpdateRCCDetailsSiebelReqABCSImpl.wsdl"/>
      <rootElement name="UpdateRCCDetailsResponse" namespace="http://www.telia.org/Siebel/getRCCBalances"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [THU AUG 10 17:33:41 IST 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:rccabcs="http://xmlns.oracle.com/ABCSImpl/Siebel/Industry//UpdateRCCDetailsSiebelReqABCSImpl/V1"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:rccabo="http://www.telia.org/Siebel/getRCCBalances"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl svcdoc rccabcs plnk xsd soap rccabo xp20 aia bpws bpel mhdr oraext dvm hwf med ids bpm xdk xref ora socket ldap">
  <xsl:template match="/">
    <rccabo:UpdateRCCDetailsResponse>
      <xsl:variable name="ConfigServiceName"
                    select="'{http://xmlns.oracle.com/ABCSImpl/Siebel/Industry//UpdateRCCDetailsSiebelReqABCSImpl/V1}UpdateRCCDetailsSiebelReqABCSImpl'"/>
      <xsl:variable name="TargetSystemID">
        <xsl:value-of select="aia:getServiceProperty($ConfigServiceName,'Default.Target.SystemID',false())"/>
      </xsl:variable>
      <xsl:variable name="TSServiceAcntId"
                    select="/rccabo:UpdateRCCDetailsRequest/rccabo:TSServiceAcntId"/>
      <xsl:variable name="ResourceID"
                    select="/rccabo:UpdateRCCDetailsRequest/rccabo:ResourceID"/>
      <xsl:variable name="CreditLimit"
                    select="/rccabo:UpdateRCCDetailsRequest/rccabo:CreditLimit"/>
      <xsl:variable name="CreditFloor"
                    select="/rccabo:UpdateRCCDetailsRequest/rccabo:CreditFloor"/>
      <xsl:variable name="XREFSourceCol" select="'SEBL_01'"/>
      <xsl:variable name="XREFTargetCol" select="$TargetSystemID"/>
      <rccabo:TSServiceAcntId>
        <xsl:value-of select="/rccabo:UpdateRCCDetailsRequest/rccabo:TSServiceAcntId"/>
      </rccabo:TSServiceAcntId>
      <rccabo:TSIPServiceId>
        <xsl:value-of select="/rccabo:UpdateRCCDetailsRequest/rccabo:TSIPServiceId"/>
      </rccabo:TSIPServiceId>
      <rccabo:TSAssetIntegrationID>
        <xsl:value-of select="/rccabo:UpdateRCCDetailsRequest/rccabo:TSAssetIntegrationID"/>
      </rccabo:TSAssetIntegrationID>
      <xsl:choose>
        <xsl:when test="$TSServiceAcntId='' or $ResourceID='' or $CreditLimit='' or $CreditFloor=''">
          <rccabo:Status>
            <rccabo:statusCode>
              <xsl:text>0</xsl:text>
            </rccabo:statusCode>
            <rccabo:errorCode>
              <xsl:text>0002</xsl:text>
            </rccabo:errorCode>
            <rccabo:errorMessage>
              <xsl:text>Missing input</xsl:text>
            </rccabo:errorMessage>
          </rccabo:Status>
        </xsl:when>
        <xsl:when test="$TSServiceAcntId!=''">
          <xsl:variable name="xrefTSServiceAcntId"
                        select="xref:lookupXRef('oramds:/apps/AIAMetaData/xref/CUSTOMERPARTY_ACCOUNTID.xref',$XREFSourceCol,$TSServiceAcntId,$XREFTargetCol,false())"/>
          <xsl:if test="$xrefTSServiceAcntId=''">
            <rccabo:Status>
              <rccabo:statusCode>
                <xsl:text>0</xsl:text>
              </rccabo:statusCode>
              <rccabo:errorCode>
                <xsl:text>0001</xsl:text>
              </rccabo:errorCode>
              <rccabo:errorMessage>
                <xsl:text>Input not valid</xsl:text>
              </rccabo:errorMessage>
            </rccabo:Status>
          </xsl:if>
        </xsl:when>
        <xsl:otherwise>
         <rccabo:Status>
              <rccabo:statusCode>
                <xsl:text>1</xsl:text>
              </rccabo:statusCode>
              <rccabo:errorCode>
                <xsl:text></xsl:text>
              </rccabo:errorCode>
              <rccabo:errorMessage>
                <xsl:text></xsl:text>
              </rccabo:errorMessage>
            </rccabo:Status>
        </xsl:otherwise>
      </xsl:choose>
    </rccabo:UpdateRCCDetailsResponse>
  </xsl:template>
</xsl:stylesheet>
