<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../UpdateRCCDetailsSiebelReqABCSImpl.wsdl"/>
      <rootElement name="UpdateRCCDetailsRequest" namespace="http://www.telia.org/Siebel/getRCCBalances"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/EnterpriseBusinessServiceLibrary/Industry/Communications/EBO/CustomerParty/V2/CommunicationsCustomerPartyEBSV2.wsdl"/>
      <rootElement name="ProcessCreditEligibilityVerificationEBM" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/CustomerParty/V2"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [WED JUL 26 00:48:48 IST 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns0="http://xmlns.oracle.com/EnterpriseServices/CustomerParty/V2"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns3="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:rccabo="http://www.telia.org/Siebel/getRCCBalances"
                xmlns:ns2="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:corecustomerpartyebs="http://xmlns.oracle.com/EnterpriseServices/Core/CustomerParty/V2"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:rccabcs="http://xmlns.oracle.com/ABCSImpl/Siebel/Industry//UpdateRCCDetailsSiebelReqABCSImpl/V1"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns5="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ns1="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/EBO/CustomerParty/V2"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:corecom="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2"
                xmlns:ns4="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04"
                xmlns:customerpartyebo="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/CustomerParty/V2"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl svcdoc plnk soap rccabo rccabcs xsd ns0 ns3 ns2 corecustomerpartyebs ns5 ns1 corecom ns4 customerpartyebo aia bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
   <xsl:import href="Xform_RCCDetailsABMReqMsg_to_CustomerPartyEBMReqMsg_Custom.xsl"/> 
  <xsl:import href="Xform_RCCDetailsABMHeader_to_CustomerPartyEBMHeader.xsl"/>
  <xsl:template match="/">
    <xsl:variable name="ConstantValue" select="1048576"/>
    <xsl:variable name="CreditFloor"
                    select="/rccabo:UpdateRCCDetailsRequest/rccabo:CreditFloor"/>
    <!-- Start MOBREL 18.4 - Defect 10344--> 
    <xsl:variable name="CreditFloorConversionValue" select="$CreditFloor * $ConstantValue"/>
    <!-- End MOBREL 18.4 - Defect 10344-->
    <customerpartyebo:ProcessCreditEligibilityVerificationEBM>
    <xsl:call-template name="EBMHeader">
      <!--xsl:with-param name="BusinessScopeIDPath" select="'/sbldata:ListOfSWIOrderIO/sbldata:SWIOrder/sbldata:OrderNumber'"/>
		<xsl:with-param name="IntegrationScenarioName" select="'Sales Order - '"/-->
      </xsl:call-template>
      <customerpartyebo:DataArea>
        <customerpartyebo:ProcessCreditEligibilityVerification>
          <corecom:Identification>
            <corecom:BusinessComponentID>
              <xsl:value-of select="/rccabo:UpdateRCCDetailsRequest/rccabo:TSIPServiceId"/>
            </corecom:BusinessComponentID>
            <corecom:ID>
              <xsl:value-of select="/rccabo:UpdateRCCDetailsRequest/rccabo:TSServiceAcntId"/>
            </corecom:ID>
            <corecom:ApplicationObjectKey>
              <corecom:ID>
                <xsl:value-of select="/rccabo:UpdateRCCDetailsRequest/rccabo:TSAssetIntegrationID"/>
              </corecom:ID>
              <corecom:ContextID>
                <xsl:value-of select="/rccabo:UpdateRCCDetailsRequest/rccabo:ResourceID"/>
              </corecom:ContextID>
            </corecom:ApplicationObjectKey>
            <corecom:AlternateObjectKey>
             <!-- Start MOBREL 18.4 - Defect 10344--> 
              <corecom:ID>
                <xsl:value-of select="$CreditFloorConversionValue"/>
              </corecom:ID>
             <!-- End MOBREL 18.4 - Defect 10344--> 
            </corecom:AlternateObjectKey>
          </corecom:Identification>
          <customerpartyebo:CreditRequestAmount>
            <xsl:value-of select="/rccabo:UpdateRCCDetailsRequest/rccabo:CreditLimit"/>
          </customerpartyebo:CreditRequestAmount>
        </customerpartyebo:ProcessCreditEligibilityVerification>
      </customerpartyebo:DataArea>
    </customerpartyebo:ProcessCreditEligibilityVerificationEBM>
  </xsl:template>
</xsl:stylesheet>
