<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/ApplicationObjectLibrary/Siebel/V1/schemas/UpdateRCCDetails.xsd"/>
      <rootElement name="UpdateRCCDetailsInput" namespace="http://www.telia.org/Siebel/getRCCBalances"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="CommunicationsCustomerPartyEBSRef.wsdl"/>
      <rootElement name="ProcessCreditEligibilityVerificationEBM" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/CustomerParty/V2"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [FRI JUN 06 11:33:00 CDT 2008]. -->
?>

<xsl:stylesheet version="2.0"
                xmlns:customerpartyebo="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/CustomerParty/V2"
		xmlns:rccabo="http://www.telia.org/Siebel/getRCCBalances"
		
		xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:corecom="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2"
                xmlns:xacml="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04"
                
		
		xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:hashmap="http://www.oracle.com/XSL/Transform/java/java.util.HashMap"
                exclude-result-prefixes="xsl xref xp20 bpws ora ehdr orcl ids hwf sbldata xacmlctx coresalesorder corecom hashmap wsa aia">
<xsl:template name="SenderType_ext">
    <!-- Customers add tranformations here -->
  </xsl:template>
  <xsl:template name="TargetType_ext">
    <!-- Customers add tranformations here -->
  </xsl:template>
  <xsl:template name="EBMHeaderType_ext">
    <!-- Customers add tranformations here -->
  </xsl:template>
  <xsl:template name="MessageProcessingInstructionType_ext">
    <!-- Customers add tranformations here -->
  </xsl:template>
  <xsl:template name="BusinessScopeType_ext">
    <!-- Customers add tranformations here -->
  </xsl:template>
  <xsl:template name="EBMTrackingType_ext">
    <!-- Customers add tranformations here -->
  </xsl:template>
  <xsl:template name="UpdateCustomerPartyType_ext">
    <!-- Customers add tranformations here -->
  </xsl:template>

</xsl:stylesheet>

