<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/ApplicationObjectLibrary/Siebel/V1/wsdls/ProductOfferWebservice.wsdl"/>
      <rootElement name="GetRecommendedProductOffers_Output" namespace="http://siebel.com/asi/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/ApplicationObjectLibrary/Siebel/V1/wsdls/ProductOfferWebservice.wsdl"/>
      <rootElement name="ApplyOfferToCreateOrder_Input" namespace="http://siebel.com/asi/"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [THU SEP 28 12:21:42 IST 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xsdLocal6="http://siebel.com/OrderManagement/Quote/Data"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:xsdLocal5="http://www.siebel.com/xml/RAFProductOfferListIO"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xsdLocal2="http://siebel.com/OrderManagement/Data/RAFProductOfferRecommendationIO"
                xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:xsdLocal1="http://www.siebel.com/xml/RAFProductOfferStructureIO"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:tns="http://siebel.com/asi/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:xsdLocal3="http://www.siebel.com/xml/RAFActionList"
                xmlns:xsdLocal4="http://siebel.com/OrderManagement/Order/Data"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl xsdLocal6 xsdLocal5 xsdLocal2 soapenc soap xsdLocal1 tns xsd xsdLocal3 xsdLocal4 aia bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    	    <tns:ApplyOfferToCreateOrder_Input>
      <xsl:for-each select='/tns:GetRecommendedProductOffers_Output/xsdLocal2:ListOfRAFProductOfferRecommendationIO/xsdLocal2:Document'>
        <xsl:if test="xsdLocal2:RecommendedProduct/xsdLocal2:Reason = 'Barring'">
          <tns:OfferId>
            <xsl:value-of select="xsdLocal2:RecommendedProduct/xsdLocal2:ProductOfferId"/>
          </tns:OfferId>
          <tns:Response>
            <xsl:text disable-output-escaping="yes">Accept</xsl:text>
          </tns:Response>
          <tns:AssetId>
            <xsl:value-of select="xsdLocal2:DocId"/>
          </tns:AssetId>
          <tns:AccountId>
            <xsl:value-of select="xsdLocal2:AccountId"/>
          </tns:AccountId>
          <tns:TS_spcTrigger_spccontext>
            <xsl:value-of select="xsdLocal2:RecommendedProduct/xsdLocal2:Reason"/>
          </tns:TS_spcTrigger_spccontext>
          <tns:ResponseId>
            <xsl:text disable-output-escaping="yes">0CM-1E5OB7</xsl:text>
          </tns:ResponseId>
          <tns:Mode>
            <xsl:text disable-output-escaping="yes">Order</xsl:text>
          </tns:Mode>
        </xsl:if>
      </xsl:for-each>
    	</tns:ApplyOfferToCreateOrder_Input>
  </xsl:template>
</xsl:stylesheet>
