<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="UpdateBillingBillNowSiebelCommsProvABCSImpl.wsdl"/>
      <rootElement name="inp1" namespace="http://xmlns.oracle.com/BRM/schemas/BusinessOpcodes"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="AIASessionPoolManagerRef.wsdl"/>
      <rootElement name="GetAIASessionPoolManagerGetRequest" namespace="http://xmlns.oracle.com/AIASessionPoolManager"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [FRI JUN 06 11:33:00 CDT 2008]. -->
?>
<xsl:stylesheet version="2.0"
                xmlns:client="http://xmlns.oracle.com/AIASessionPoolManager"
		xmlns:ns1ebo="http://xmlns.oracle.com/BRM/schemas/BusinessOpcodes"
		
		
		xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:corecom="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2"
                xmlns:xacml-context="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04"
                
		
		
		xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:str="http://www.oracle.com/XSL/Transform/java/java.lang.String"
                exclude-result-prefixes="xsl xacml-context xref xp20 bpws ora ehdr orcl ids hwf aia wsa corecom coresalesorder sblorderdata sblasi str">

  <xsl:import href="Xform_BillingBillNowReqMsg_to_AIASessionPoolManagerRespMsg_Custom.xsl"/>
  <xsl:import href="Xform_BillingBillNowReqHeader_to_AIASessionPoolManagerRespHeader.xsl"/>

  <!-- define all your parameters and variable names here -->
   
  <xsl:variable name="TargetSystemID" select="/ns1ebo:inp1/corecom:EBMHeader/corecom:Target/corecom:ID"/>
  <xsl:variable name="XREFTargetCol" select="$TargetSystemID"/>
  <xsl:variable name="XREFSourceCol" select="'COMMON'"/>
  
  <xsl:template match="/">
    <xsl:apply-templates select="ns1ebo:inp1"/>

    <!-- do xref population for newly inserted lines -->    
    <!-- sample code for xref population
    <xsl:choose>
        <xsl:when test="coresalesorder:UpdateSalesOrderEBM/coresalesorder:DataArea/coresalesorder:UpdateSalesOrder/coresalesorder:TypeCode='QUOTE'">
            <xsl:for-each select="$SBLQuoteUpsert_Output/sblquotedata:ListOfSWIQuoteIO/sblquotedata:SWIQuote/sblquotedata:ListOfSWIQuoteItem/sblquotedata:SWIQuoteItem[@operation='insert']">
                <xsl:variable name="InsertQuoteLineXrefId" select="xref:populateXRefRow('QUOTE_LINEID',$XREFSourceCol,sblquotedata:AIAIntegrationId,$XREFTargetCol,sblquotedata:Id,'ANY')"/>
            </xsl:for-each>
        </xsl:when>
        <xsl:otherwise>
            <xsl:for-each select="$SBLOrderUpsert_Output/sblorderdata:ListOfSWIOrderIO/sblorderdata:SWIOrder/sblorderdata:ListOfSWIOrderItem/sblorderdata:SWIOrderItem[@operation='insert']">
                <xsl:variable name="InsertOrderLineXrefId" select="xref:populateXRefRow('SALESORDER_LINEID',$XREFSourceCol,sblorderdata:AIAIntegrationId,$XREFTargetCol,sblorderdata:Id,'ANY')"/>
            </xsl:for-each>
        </xsl:otherwise>
    </xsl:choose>
    -->

  </xsl:template>

  <xsl:template match="ns1ebo:inp1">
    <client:GetAIASessionPoolManagerGetRequest>
        <xsl:apply-templates select="@*|node()"/>
    </client:GetAIASessionPoolManagerGetRequest>
  </xsl:template>

   <xsl:template match="client:DataArea">
        <client:DataArea>
            <corecom:Update/>
	<!--- Call your data mapping template here 
	Sample Data mapping template call
           <xsl:apply-templates select="sbldata:ListOfSWIOrderIO/sbldata:SWIOrder"/>
	-->

	</client:DataArea>
  </xsl:template>

  

  <xsl:template match="@*|node()">
    <!--xsl:param name="LineIndex" select="0"/-->
    <xsl:copy>
        <xsl:apply-templates select="@*|node()">
            <!--xsl:with-param name="LineIndex" select="$LineIndex"/-->
        </xsl:apply-templates>
    </xsl:copy>
  </xsl:template>


</xsl:stylesheet>
