<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/ApplicationObjectLibrary/PIM/V1/wsdls/ItemService.wsdl"/>
      <rootElement name="ItemService_GetItemInformationResponse" namespace="http://oracle.apps.ego.item.service/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/EnterpriseObjectLibrary/Core/EBO/Item/V2/ItemEBM.xsd"/>
      <rootElement name="QueryItemListResponseEBM" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/Item/V2"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.1.0(build 061009.0802) AT [MON AUG 11 20:09:42 IST 2008]. -->
?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ns1="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/Item/V2" 
	xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions" 
	 xmlns:ebi="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
	xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1" 
	xmlns:corecomEBO="http://xmlns.oracle.com/EnterpriseObjects/Core/CommonEBO/V1" xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing" 
	xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns2="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/CommonEBO/V1" 
	xmlns:coreitemcust="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/EBO/Item/V2" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" 
	xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xacml-context="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04" 
	xmlns:corecomcust="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
	xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" 
	xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://xmlns.oracle.com/apps/ego/item/service" 
	xmlns:xacml="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04" 
	xmlns:corecom="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2" 
	exclude-result-prefixes="xsl xsd ns0 ns1 svcdoc corecomEBO wsa ns2 coreitemcust xacml-context corecomcust xacml corecom bpws aia ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template name="MessageProcessingInstructionType_ext"/>
  <xsl:template name="SenderType_ext"/>
  <xsl:template name="TargetType_ext"/>
  <xsl:template name="BusinessScopeType_ext"/>
  <xsl:template name="EBMTrackingType_ext"/>
  <xsl:template name="EBMHeaderType_ext"/>
  <xsl:template name="ItemCatalogReferenceType_ext"/>
  <xsl:template name="ItemCatalogType_ext"/>
  <xsl:template name="SpecificationType_ext"/>
  <xsl:template name="SpecificationGroupType_ext"/>
  <xsl:template name="ItemSpecificationGroupType_ext"/>
  <xsl:template name="ItemLifecycleCharacteristicsType_ext"/>
  <xsl:template name="ItemPhysicalCharacteristicsType_ext"/>
  <xsl:template name="InventoryCharacteristicsType_ext"/>
  <xsl:template name="ItemPurchasingCharacteristicsType_ext"/>
  <xsl:template name="ReorderCharacteristicsType_ext"/>
  <xsl:template name="ProcessingLeadTimeCharacteristicsType_ext"/>
  <xsl:template name="MinMaxCharacteristicsType_ext"/>
  <xsl:template name="ItemPlanningCharacteristicsType_ext"/>
  <xsl:template name="ItemManufacturingCharacteristicsType_ext"/>
  <xsl:template name="BaseModelItemReferenceType_ext"/>
  <xsl:template name="ItemOrderManagementCharacteristicsType_ext"/>
  <xsl:template name="ItemServiceCharacteristicsType_ext"/>
  <xsl:template name="ItemRevisionHistoryType_ext"/>
  <xsl:template name="InventoryLocationType_ext"/>
  <xsl:template name="ItemGLAcccountType_ext"/>
  <xsl:template name="QueryItemListResponseType_ext"/>
</xsl:stylesheet>
