<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/EnterpriseObjectLibrary/Core/EBO/BillOfMaterials/V1/BillOfMaterialsEBM.xsd"/>
      <rootElement name="SyncBillOfMaterialsListEBM" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/BillOfMaterials/V1"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/EnterpriseObjectLibrary/Core/EBO/BillOfMaterials/V1/BillOfMaterialsEBM.xsd"/>
      <rootElement name="SyncBillOfMaterialsListEBM" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/BillOfMaterials/V1"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [WED JUL 15 13:48:53 IST 2009]. -->
?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:corebillofmaterialscust="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/EBO/BillOfMaterials/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1" xmlns:corecomEBO="http://xmlns.oracle.com/EnterpriseObjects/Core/CommonEBO/V1" xmlns:ns0="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/BillOfMaterials/V1" xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns1="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/CommonEBO/V1" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xacml-context="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:corecomcust="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xacml="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04" xmlns:corecom="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2" exclude-result-prefixes="xsl corebillofmaterialscust xsd svcdoc corecomEBO ns0 wsa ns1 xacml-context corecomcust xacml corecom bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
      <xsl:template match="/">
            <ns0:SyncBillOfMaterialsListEBM>
                  <xsl:apply-templates select="ns0:SyncBillOfMaterialsListEBM/corecom:EBMHeader"/>
                  <xsl:for-each select="/ns0:SyncBillOfMaterialsListEBM/ns0:DataArea">
                        <ns0:DataArea>
                              <xsl:apply-templates select="corecom:Sync"/>
                              <ns0:SyncBillOfMaterialsList>
                                    <xsl:apply-templates select="ns0:SyncBillOfMaterialsList/corecom:Identification"/>
                                    <xsl:apply-templates select="ns0:SyncBillOfMaterialsList/corecom:TypeCode"/>
                                    <xsl:apply-templates select="ns0:SyncBillOfMaterialsList/corecom:Name"/>
                                    <xsl:apply-templates select="ns0:SyncBillOfMaterialsList/corecom:ImplementationDate"/>
                                    <xsl:apply-templates select="ns0:SyncBillOfMaterialsList/corecom:EffectivityControlCode"/>
                                    <xsl:apply-templates select="ns0:SyncBillOfMaterialsList/corecom:ItemReference"/>
                                    <xsl:apply-templates select="ns0:SyncBillOfMaterialsList/corecomEBO:EngineeringIndicator"/>
                                    <xsl:apply-templates select="ns0:SyncBillOfMaterialsList/corecomEBO:ItemStructureSpecificationGroup"/>
                                    <xsl:for-each select="ns0:SyncBillOfMaterialsList/corecomEBO:BillOfMaterialsComponentItem">
                                          <corecomEBO:BillOfMaterialsComponentItem>
                                                <xsl:apply-templates select="corecom:Quantity"/>
                                                <xsl:apply-templates select="corecom:BasisQuantity"/>
                                                <xsl:apply-templates select="corecom:OptionalIndicator"/>
                                                <xsl:apply-templates select="corecom:MutuallyExclusiveOptionIndicator"/>
                                                <xsl:apply-templates select="corecom:CostRollupInclusionIndicator"/>
                                                <xsl:apply-templates select="corecom:ATPCheckRequiredIndicator"/>
                                                <xsl:apply-templates select="corecom:ShippingAllowedIndicator"/>
                                                <xsl:apply-templates select="corecom:ShippingDocumentVisibilityIndicator"/>
                                                <xsl:apply-templates select="corecom:ToUnitNumber"/>
                                                <xsl:apply-templates select="corecom:MinimumOrderQuantity"/>
                                                <xsl:apply-templates select="corecom:MaximumOrderQuantity"/>
                                                <xsl:apply-templates select="corecom:AutoRequestIndicator"/>
                                                <xsl:apply-templates select="corecom:RequiredToShipIndicator"/>
                                                <xsl:apply-templates select="corecom:RequiredForRevenueIndicator"/>
                                                <xsl:apply-templates select="corecom:Note"/>
                                                <xsl:apply-templates select="corecom:EffectiveTimePeriod"/>
                                                <xsl:apply-templates select="corecom:ItemReference"/>
                                                <xsl:apply-templates select="corecom:InventoryLocationReference"/>
                                                <xsl:apply-templates select="corecomEBO:YieldFactor"/>
                                                <xsl:apply-templates select="corecomEBO:PlanningQuantityMultiplier"/>
                                                <xsl:apply-templates select="corecom:Name"/>
                                                <xsl:apply-templates select="corecom:TypeCode"/>
                                                <xsl:apply-templates select="corecom:DefaultIndicator"/>
                                                <xsl:apply-templates select="corecom:MaximumQuantity"/>
                                                <xsl:apply-templates select="corecom:MinimumQuantity"/>
                                                <xsl:apply-templates select="corecom:DefaultQuantity"/>
                                                <xsl:apply-templates select="corecomEBO:ComponentItemSpecificationGroup"/>
                                                <xsl:apply-templates select="corecom:ClassificationReference"/>
                                          </corecomEBO:BillOfMaterialsComponentItem>
                                    </xsl:for-each>
                                    <xsl:apply-templates select="ns0:SyncBillOfMaterialsList//corecomEBO:BillOfMaterialsComponentItemExclusion"/>
                                    <xsl:apply-templates select="ns0:SyncBillOfMaterialsList/corecomEBO:BillOfMaterialsSpecificationDefaultValueOverride"/>
                                    <xsl:apply-templates select="ns0:SyncBillOfMaterialsList/corecomEBO:BillOfMaterialsSpecificationValueExclusion"/>
                              </ns0:SyncBillOfMaterialsList>
                        </ns0:DataArea>
                  </xsl:for-each>
            </ns0:SyncBillOfMaterialsListEBM>
      </xsl:template>
      <xsl:template match="*">
            <xsl:element name="{name()}">
                  <xsl:apply-templates select="@*|node()"/>
            </xsl:element>
      </xsl:template>
      <xsl:template match="@*|text()|comment()|processing-instruction()">
            <xsl:copy>
                  <xsl:apply-templates select="@*|node()"/>
            </xsl:copy>
      </xsl:template>
</xsl:stylesheet>
