<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/EnterpriseObjectLibrary/Core/EBO/Item/V2/ItemEBM.xsd"/>
      <rootElement name="SyncItemListEBM" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/Item/V2"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/EnterpriseObjectLibrary/Core/EBO/Item/V2/ItemEBM.xsd"/>
      <rootElement name="SyncItemListEBM" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/Item/V2"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [FRI OCT 23 12:14:56 IST 2009]. -->
?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ns0="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/Item/V2" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1" xmlns:corecomEBO="http://xmlns.oracle.com/EnterpriseObjects/Core/CommonEBO/V1" xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns1="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/CommonEBO/V1" xmlns:coreitemcust="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/EBO/Item/V2" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xacml-context="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:corecomcust="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xacml="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04" xmlns:corecom="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2" exclude-result-prefixes="xsl ns0 xsd svcdoc corecomEBO wsa ns1 coreitemcust xacml-context corecomcust xacml corecom bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
  
  
  <xsl:variable name="XREFSourceCol">
    <xsl:value-of select="&quot;COMMON&quot;"/>
  </xsl:variable>
    
    <ns0:SyncItemListEBM>
              <xsl:apply-templates select="@*"/>
                 <xsl:apply-templates select="/ns0:SyncItemListEBM/corecom:EBMHeader"/>
             <xsl:variable name="TargetSystem">
                     <xsl:value-of select="/ns0:SyncItemListEBM/corecom:EBMHeader/corecom:Target/corecom:ID"/>
            </xsl:variable>
            <xsl:variable name="XREFTargetCol">
                     <xsl:value-of select="/ns0:SyncItemListEBM/corecom:EBMHeader/corecom:Sender/corecom:ID"/>
            </xsl:variable>
            <xsl:variable name="PIMTargetSystem">
              <xsl:value-of select="dvm:lookupValue(&quot;oramds:/apps/AIAMetaData/dvm/TARGET_ID.dvm&quot;,$XREFSourceCol,$TargetSystem,$XREFTargetCol,&quot;&quot;)"/>
            </xsl:variable>
 
      <xsl:for-each select="/ns0:SyncItemListEBM/ns0:DataArea">
           
             <xsl:variable name="SystemFlag">
                     <xsl:value-of select="ns0:SyncItemList/corecomEBO:ItemSpecificationGroup/corecom:SpecificationGroup[corecom:Name='Destination_Sys_Specification' and corecom:Specification[corecom:Name='Destination_System' and corecom:ValueText=$PIMTargetSystem]]/corecom:Specification[corecom:Name='Sync_Item']/corecom:ValueText"/>
            </xsl:variable>
             <xsl:variable name="SystemFlagExist">
                     <xsl:value-of select="count(ns0:SyncItemList/corecomEBO:ItemSpecificationGroup/corecom:SpecificationGroup[corecom:Name='Destination_Sys_Specification'])"/>
            </xsl:variable>
          
                     <xsl:choose>
                        <xsl:when test="$SystemFlagExist = 0">
                               <xsl:copy-of select="."/>
                        </xsl:when>
                        <xsl:when test="$SystemFlagExist > 0 and ($SystemFlag='' or $SystemFlag='Y') ">
                             <xsl:copy-of select="."/>
                        </xsl:when>
                        <xsl:otherwise>
                        </xsl:otherwise>
                      </xsl:choose>    
                      
      </xsl:for-each>
    
    </ns0:SyncItemListEBM>
  </xsl:template>
    
  <xsl:template match="@*|node()">
    <xsl:copy>
        <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>  
  </xsl:template>
</xsl:stylesheet>
