<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/EnterpriseObjectLibrary/Industry/Communications/EBO/TroubleTicket/V1/TroubleTicketEBM.xsd"/>
      <rootElement name="UpdateTroubleTicketEBM" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/TroubleTicket/V1"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/ApplicationObjectLibrary/Siebel/V1/wsdls/SWITroubleTicketIO.wsdl"/>
      <rootElement name="SWITroubleTicketInsertOrUpdate_Input" namespace="http://siebel.com/asi/"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [FRI DEC 18 15:27:06 IST 2009]. -->
?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1" xmlns:corecomEBO="http://xmlns.oracle.com/EnterpriseObjects/Core/CommonEBO/V1" xmlns:tns="http://siebel.com/asi/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd1="http://www.siebel.com/xml/SWITroubleTicketIO" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xacml-context="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:corecomcust="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ns0="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/TroubleTicket/V1" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xacml="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04" xmlns:corecom="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2" xmlns:coretroubleticketcust="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/EBO/TroubleTicket/V1" exclude-result-prefixes="xsl xsd svcdoc corecomEBO wsa xacml-context corecomcust ns0 xacml corecom coretroubleticketcust tns soap xsd1 soapenc bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
    <xsl:template name="ListOfSWITroubleTicketIO_ext">
      <!-- Customers add tranformations here -->
    </xsl:template>
    <xsl:template name="TroubleTicket_ext">
      <!-- Customers add tranformations here -->
    </xsl:template>
    <xsl:template name="ListOfSWIOrderFailure_ext">
      <!-- Customers add tranformations here -->
    </xsl:template>
    <xsl:template name="SWIOrderFailure_ext">
    <!-- Customers add tranformations here -->
  </xsl:template>
</xsl:stylesheet>
