<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../UpdateRCCDetailsBRMProvABCSImpl.wsdl"/>
      <rootElement name="UpdateCustomerPartyEBM" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/CustomerParty/V2"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/ApplicationObjectLibrary/BRM/V1/wsdls/BRMBillServices.wsdl"/>
      <rootElement name="TLC_OP_BILL_SET_LIMIT_AND_CR_inputFlist" namespace="http://xmlns.oracle.com/BRM/schemas/BusinessOpcodes"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [MON JUL 24 17:13:04 IST 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:brm="http://xmlns.oracle.com/BRM/schemas/BusinessOpcodes"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns2="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:customerpartyeboabcs="http://xmlns.oracle.com/ABCSImpl/BRM/Industry//UpdateRCCDetailsBRMProvABCSImpl/V1"
                xmlns:ns1="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns5="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ns0="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/EBO/CustomerParty/V2"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns3="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2"
                xmlns:ns4="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04"
                xmlns:customerpartyeboebo="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/CustomerParty/V2"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl svcdoc plnk soap ns2 customerpartyeboabcs ns1 ns5 ns0 xsd ns3 ns4 customerpartyeboebo brm jca aia bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <xsl:variable name="TargetSystemID"
                  select="/customerpartyeboebo:UpdateCustomerPartyEBM/ns3:EBMHeader/ns3:Target/ns3:ID"/>
    <xsl:variable name="XREFSourceCol" select='"SEBL_01"'/>
    <xsl:variable name="XREFTargetCol" select="$TargetSystemID"/>
    <xsl:variable name="AccountId"
                  select="/customerpartyeboebo:UpdateCustomerPartyEBM/customerpartyeboebo:DataArea/customerpartyeboebo:UpdateCustomerParty/ns3:Identification/ns3:ID"/>
    <xsl:variable name="AssetIntegrationId"
                  select="/customerpartyeboebo:UpdateCustomerPartyEBM/customerpartyeboebo:DataArea/customerpartyeboebo:UpdateCustomerParty/ns3:Identification/ns3:ApplicationObjectKey/ns3:ID"/>
    <brm:TLC_OP_BILL_SET_LIMIT_AND_CR_inputFlist>
      <brm:LIMIT>
        <xsl:attribute name="elem">
          <xsl:value-of select="/customerpartyeboebo:UpdateCustomerPartyEBM/customerpartyeboebo:DataArea/customerpartyeboebo:UpdateCustomerParty/customerpartyeboebo:CustomerPartyCreditProfile/ns3:Identification/ns3:ID"/>
        </xsl:attribute>
        <brm:CREDIT_FLOOR>
          <xsl:value-of select="/customerpartyeboebo:UpdateCustomerPartyEBM/customerpartyeboebo:DataArea/customerpartyeboebo:UpdateCustomerParty/customerpartyeboebo:CustomerPartyCreditProfile/customerpartyeboebo:CreditRatingCode"/>
        </brm:CREDIT_FLOOR>
        <brm:CREDIT_LIMIT>
          <xsl:value-of select="/customerpartyeboebo:UpdateCustomerPartyEBM/customerpartyeboebo:DataArea/customerpartyeboebo:UpdateCustomerParty/customerpartyeboebo:CustomerPartyCreditProfile/customerpartyeboebo:CreditLimitAmount"/>
        </brm:CREDIT_LIMIT>
      </brm:LIMIT>
      <brm:POID>
        <xsl:value-of select='xref:lookupXRef("oramds:/apps/AIAMetaData/xref/CUSTOMERPARTY_ACCOUNTID.xref",$XREFSourceCol,$AccountId,$XREFTargetCol,false())'/>
      </brm:POID>
      <brm:PROGRAM_NAME>
        <xsl:text disable-output-escaping="no">AIA</xsl:text>
      </brm:PROGRAM_NAME>
      <brm:SERVICE_ID>
        <xsl:value-of select="/customerpartyeboebo:UpdateCustomerPartyEBM/customerpartyeboebo:DataArea/customerpartyeboebo:UpdateCustomerParty/ns3:Identification/ns3:BusinessComponentID"/>
      </brm:SERVICE_ID>
      <xsl:choose>
      <xsl:when test="$AssetIntegrationId!=''">
        <brm:SERVICE_OBJ>
        <xsl:value-of select='xref:lookupXRef("oramds:/apps/AIAMetaData/xref/INSTALLEDPRODUCT_ID.xref",$XREFSourceCol,$AssetIntegrationId,$XREFTargetCol,false())'/>
      </brm:SERVICE_OBJ>
      </xsl:when>
      <xsl:otherwise>
      <brm:SERVICE_OBJ>
      </brm:SERVICE_OBJ>
      </xsl:otherwise>
      </xsl:choose>
    </brm:TLC_OP_BILL_SET_LIMIT_AND_CR_inputFlist>
  </xsl:template>
</xsl:stylesheet>
