<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/EnterpriseObjectLibrary/Core/EBO/Item/V2/ItemEBM.xsd"/>
      <rootElement name="SyncItemListEBM" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/Item/V2"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../../../Bethpage%20Devops/SyncProductSiebelProvABCSImpl/SWIProductLineRef.wsdl"/>
      <rootElement name="SWIProductLine_Upsert_Input" namespace="http://siebel.com/asi/"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.5.0(build 110418.1550.0174) AT [THU JUN 05 15:00:03 IST 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:corecomEBO="http://xmlns.oracle.com/EnterpriseObjects/Core/CommonEBO/V1"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xsdLocal2="http://www.siebel.com/xml/SWIAdminProductLine/Data"
                xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:corecomcust="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsdLocal3="http://www.siebel.com/xml/SWIAdminProductLine/Id"
                xmlns:ns0="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/Item/V2"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xacml="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04"
                xmlns:tns="http://siebel.com/asi/"
                xmlns:coreitemcust="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/EBO/Item/V2"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:corecom="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2"
                xmlns:xsdLocal1="http://www.siebel.com/xml/SWIAdminProductLine"
                xmlns:xacml-context="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04"
                xmlns:xsdLocal4="http://www.siebel.com/xml/SWIAdminProductLine/Query"
                xmlns:ns1="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/CommonEBO/V1"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl svcdoc corecomEBO corecomcust wsa ns0 xacml coreitemcust xsd corecom xacml-context ns1 xsdLocal2 soapenc soap xsdLocal3 tns xsdLocal1 xsdLocal4 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
                
		   <xsl:include href="XformSyncItemListEBMToSWIUpsertProductLine_Custom.xsl"/>

                  <xsl:param name="SystemID"/>
                  <xsl:param name="DataAreaIndex"/>
                  <xsl:param name="ProductLineIndex"/>
                  <xsl:template match="/">
                  <xsl:variable name="XREFSourceCol">
                    <xsl:value-of select="'COMMON'"/>
                  </xsl:variable>
                  <xsl:variable name="XREFTargetCol" select="$SystemID"/>
                  <xsl:variable name="DataAreaId" select="number($DataAreaIndex)"/>
                  <xsl:variable name="ProductLineId" select="number($ProductLineIndex)"/>
                   <xsl:for-each select="ns0:SyncItemListEBM/ns0:DataArea[$DataAreaId]">
                    <tns:SWIProductLine_Upsert_Input>
                      <xsdLocal1:ListOfAdminProductLine>
                        <xsdLocal1:AdminProductLine>
                          <!--xsdLocal1:Description>
                            <xsl:value-of select="/ns0:SyncItemListEBM/ns0:DataArea/ns0:SyncItemList/corecomEBO:Description"/>
                          </xsdLocal1:Description-->
                          <xsdLocal1:Name>
                            <xsl:value-of select="ns0:SyncItemList/corecomEBO:ItemClassification/corecomEBO:ProductLine[$ProductLineId]"/>
                          </xsdLocal1:Name>
                          <!--xsdLocal1:ListOfAdminProductLine_Position>
                            <xsdLocal1:AdminProductLine_Position>
                              <xsdLocal1:Position>
                                <xsl:value-of select="/ns0:SyncItemListEBM/ns0:DataArea/ns0:SyncItemList/corecomEBO:ServiceIndicator"/>
                              </xsdLocal1:Position>
                              <xsdLocal1:ProductLineManager>
                                <xsl:value-of select="/ns0:SyncItemListEBM/ns0:DataArea/ns0:SyncItemList/corecomEBO:ToolIndicator"/>
                              </xsdLocal1:ProductLineManager>
                              <xsdLocal1:Division>
                                <xsl:value-of select="/ns0:SyncItemListEBM/ns0:DataArea/ns0:SyncItemList/corecomEBO:AccessPassKey"/>
                              </xsdLocal1:Division>
                            </xsdLocal1:AdminProductLine_Position>
                          </xsdLocal1:ListOfAdminProductLine_Position-->
                            <xsdLocal2:ListOfAdminProductLine_InternalProduct>
                              <xsdLocal2:AdminProductLine_InternalProduct>
                               <xsl:attribute name="IsPrimaryMVG">
                                 <xsl:value-of select="ns0:SyncItemList/corecomEBO:ItemClassification/corecomEBO:PrimaryProductLineIndicator[$ProductLineId]"/>
                               </xsl:attribute>
                                <xsdLocal2:Product>
                                  <xsl:value-of select="ns0:SyncItemList/corecomEBO:Name"/>
                                </xsdLocal2:Product>
                                <xsdLocal2:IntegrationId>
                                  <xsl:value-of select="xref:lookupXRef('oramds:/apps/AIAMetaData/xref/ITEM_ITEMID.xref',$XREFSourceCol,ns0:SyncItemList/corecom:ItemIdentification/corecom:BusinessComponentID,$XREFTargetCol,false())"/>
                                </xsdLocal2:IntegrationId>
				    <xsdLocal2:PrimaryOrganizationId>
					<xsl:value-of select="xref:lookupXRef('oramds:/apps/AIAMetaData/xref/ORGANIZATION_ID.xref',$XREFSourceCol,ns0:SyncItemList/corecom:ItemIdentification/corecom:ContextID[@schemeID='OPERATING_UNIT_ID'],$XREFTargetCol,false())"/>
					<!--xsl:value-of select="'Vision Operations'"/-->
				    </xsdLocal2:PrimaryOrganizationId>
                              </xsdLocal2:AdminProductLine_InternalProduct>
                            </xsdLocal2:ListOfAdminProductLine_InternalProduct>
                        </xsdLocal1:AdminProductLine>
                      </xsdLocal1:ListOfAdminProductLine>
                    </tns:SWIProductLine_Upsert_Input>
                   </xsl:for-each>
                  </xsl:template>
</xsl:stylesheet>
