<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/EnterpriseObjectLibrary/Core/EBO/Item/V2/ItemEBM.xsd"/>
      <rootElement name="SyncItemListEBM" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/Item/V2"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../../../DIT%20Devops/SyncProductSiebelProvABCSImpl/SWIProductLineRef.wsdl"/>
      <rootElement name="SWIProductLine_Synchronize_Input" namespace="http://siebel.com/asi/"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.5.0(build 110418.1550.0174) AT [MON DEC 01 17:56:02 IST 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:corecomEBO="http://xmlns.oracle.com/EnterpriseObjects/Core/CommonEBO/V1"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xsdLocal5="http://www.siebel.com/xml/SWIAdminProductLine/Data"
                xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:corecomcust="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsdLocal3="http://www.siebel.com/xml/SWIAdminProductLine/Id"
                xmlns:ns0="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/Item/V2"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xacml="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04"
                xmlns:tns="http://siebel.com/asi/"
                xmlns:coreitemcust="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/EBO/Item/V2"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:corecom="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2"
                xmlns:xsdLocal2="http://www.siebel.com/xml/SWIAdminProductLine"
                xmlns:xacml-context="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04"
                xmlns:xsdLocal4="http://www.siebel.com/xml/SWIAdminProductLine/Query"
                xmlns:ns1="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/CommonEBO/V1"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl svcdoc corecomEBO corecomcust wsa ns0 xacml coreitemcust xsd corecom xacml-context ns1 xsdLocal2 soapenc soap xsdLocal3 tns xsdLocal1 xsdLocal4 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
				
				<xsl:include href="XformSyncItemListEBMToSWISyncProductLine_Custom.xsl"/>
				
				
  <xsl:param name="ProdLineDataAreaCount"/>
      <xsl:template match="/">
      <xsl:param name="SystemID"/>
      <xsl:variable name="XREFTargetCol">
        <xsl:value-of select="'COMMON'"/>
      </xsl:variable>
      <xsl:variable name="DataAreaCount" select="number($ProdLineDataAreaCount)"/>
      <xsl:variable name="XREFSourceCol" select="$SystemID"/>
    <tns:SWIProductLine_Synchronize_Input>
      <xsdLocal2:ListOfAdminProductLine>
	   <xsl:for-each select="/ns0:SyncItemListEBM/ns0:DataArea[$DataAreaCount]">
		<xsdLocal2:AdminProductLine>
		  <xsdLocal2:Description>
			<xsl:value-of select="ns0:SyncItemList/corecomEBO:Description"/>
		  </xsdLocal2:Description>
		  <xsdLocal2:Name>
			<xsl:value-of select="ns0:SyncItemList/corecomEBO:Name"/>
		  </xsdLocal2:Name>
		   <xsl:for-each select="ns0:SyncItemList/corecomEBO:ItemSpecificationGroup/corecom:SpecificationGroup[corecom:Name='Product_Line_Additional_Info']/corecom:Specification">
			<xsl:if test="corecom:Name = 'Contracting'">
			  <xsdLocal2:Contracting>
				<xsl:value-of select="corecom:ValueText"/>
			  </xsdLocal2:Contracting>
			</xsl:if>
			<xsl:if test="corecom:Name = 'Licensing'">
			  <xsdLocal2:Licensing>
				<xsl:value-of select="corecom:ValueText"/>
			  </xsdLocal2:Licensing>
			</xsl:if>
		   </xsl:for-each>
		</xsdLocal2:AdminProductLine>
		</xsl:for-each>
	  </xsdLocal2:ListOfAdminProductLine>
    </tns:SWIProductLine_Synchronize_Input>
  </xsl:template>
</xsl:stylesheet>
