<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/ApplicationObjectLibrary/Siebel/V1/wsdls/SWIPromotionIntegrationIO.wsdl"/>
      <rootElement name="SWIPromotionUpsert_Output" namespace="http://siebel.com/asi/SWIPromotionIntegration/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/EnterpriseObjectLibrary/Core/EBO/Item/V2/ItemEBM.xsd"/>
      <rootElement name="SyncItemListResponseEBM" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/Item/V2"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [THU MAY 28 20:49:54 IST 2009]. -->
?>
<xsl:stylesheet version="1.0" xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions" xmlns:tns="http://siebel.com/asi/SWIPromotionIntegration/V0" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:corecomEBO="http://xmlns.oracle.com/EnterpriseObjects/Core/CommonEBO/V1" xmlns:coreEBOcust="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/CommonEBO/V1" xmlns:corecomcust="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2" xmlns:corecom="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2" xmlns:coreeboitem="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/Item/V2" xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1" xmlns:coreitemcust="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/EBO/Item/V2" xmlns:xsdLocal="http://www.siebel.com/xml/SWIPromotionIntegrationIO" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xacml="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" exclude-result-prefixes="xsl xref xp20 bpws ora ehdr orcl ids hwf" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">

<!--  User Defined Templates for XSL Extension -->
  <xsl:template name="MessageProcessingInstructionType_ext">
    <!-- Customers add tranformations here -->
  </xsl:template>
  <xsl:template name="SenderType_ext">
    <!-- Customers add tranformations here -->
  </xsl:template>  
  <xsl:template name="BusinessScopeType_ext">
    <!-- Customers add tranformations here -->
  </xsl:template> 
  <xsl:template name="EBMTrackingType_ext">
    <!-- Customers add tranformations here -->
  </xsl:template>
  <xsl:template name="EMBHeaderType_ext">
    <!-- Customers add tranformations here -->
  </xsl:template>

  <xsl:template name="SyncItemListResponseType_ext">
    <!-- Customers add tranformations here -->
  </xsl:template>
	  <xsl:template name="InventoryLocationType_ext">
	    <!-- Customers add tranformations here -->
	  </xsl:template>

</xsl:stylesheet>
