<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/ApplicationObjectLibrary/PDC/wsdls/PricingGateway.wsdl"/>
      <rootElement name="PDCResponse" namespace="http://www.oracle.com/communications/pricing"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/ApplicationConnectorServiceLibrary/PDC/V1/ProviderABCS/SyncItemListPDCProvABCSImpl.wsdl"/>
      <rootElement name="Fault" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [MON DEC 15 17:05:06 IST 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns1="http://xmlns.oracle.com/communications/platform/model/pricing"
                xmlns:ns3="http://xmlns.oracle.com/EnterpriseObjects/Core/CommonEBO/V1"
                xmlns:tns="urn:PricingGateWay"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ejb="http://schemas.xmlsoap.org/wsdl/ejb/"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:format="http://schemas.xmlsoap.org/wsdl/formatbinding/"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns8="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:eboabcs="http://xmlns.oracle.com/ABCSImpl/PDC/Core/SyncItemListPDCProvABCSImpl/V1"
                xmlns:ns0="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:ns2="http://schemas.oracle.com/service/bpel/common"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:pricinggateway="http://www.oracle.com/communications/pricing"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:eboebo="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/Item/V2"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns4="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04"
                xmlns:ns6="http://xmlns.oracle.com/communications/platform/model/Common"
                xmlns:ns5="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/EBO/Item/V2"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns7="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2"
                xmlns:ns9="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04"
                xmlns:ns10="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/CommonEBO/V1"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns ejb soap12 format soap mime pricinggateway xsd svcdoc ns1 ns3 plnk ns8 eboabcs ns0 ns2 eboebo ns4 ns6 ns5 ns7 ns9 ns10 aia bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <ns7:Fault>
      <ns7:FaultNotification>
        <ns7:FaultMessage>
        <ns7:Text>
          <xsl:for-each select="/pricinggateway:PDCResponse/pricinggateway:validationError">            
            <xsl:value-of select="." />
          </xsl:for-each>
          </ns7:Text>
        </ns7:FaultMessage>
      </ns7:FaultNotification>
    </ns7:Fault>
  </xsl:template>
</xsl:stylesheet>
