<?xml version='1.0' encoding='UTF-8'?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/ApplicationConnectorServiceLibrary/PDC/V1/ProviderABCS/SyncItemListPDCProvABCSImpl.wsdl"/>
      <rootElement name="SyncItemListEBM" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/Item/V2"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="ItemEBSResponseRef.wsdl"/>
      <rootElement name="SyncItemListResponseEBM" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/Item/V2"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [FRI JUN 06 11:33:00 CDT 2008]. -->
?>
<xsl:stylesheet version="2.0" xmlns:ebo="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/Item/V2" xmlns:eboebo="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/Item/V2" xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions" xmlns:corecom="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2" xmlns:xacml-context="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:str="http://www.oracle.com/XSL/Transform/java/java.lang.String" xmlns:corecomEBO="http://xmlns.oracle.com/EnterpriseObjects/Core/CommonEBO/V1" exclude-result-prefixes="xsl xacml-context xref xp20 bpws ora ehdr orcl ids hwf aia wsa corecom corecomEBO coresalesorder sblorderdata sblasi str">
   <xsl:import href="Xform_ItemListReqMsg_to_ItemRespMsg_Custom.xsl"/>
   <xsl:import href="Xform_ItemListReqHeader_to_ItemRespHeader.xsl"/>
   <xsl:variable name="TargetSystemID" select="/eboebo:SyncItemListEBM/corecom:EBMHeader/corecom:Target/corecom:ID"/>
   <xsl:variable name="XREFTargetCol" select="$TargetSystemID"/>
   <xsl:variable name="XREFSourceCol" select="'COMMON'"/>
   <xsl:template match="eboebo:SyncItemListEBM">
      <ebo:SyncItemListResponseEBM>
         <xsl:apply-templates select="corecom:EBMHeader"/>
         <xsl:apply-templates select="ebo:DataArea"/>
      </ebo:SyncItemListResponseEBM>
   </xsl:template>
   <xsl:template match="ebo:DataArea">
      <ebo:DataArea>
         <corecom:Sync/>
         <ebo:SyncItemListResponse>
            <xsl:copy-of select="ebo:SyncItemList/corecom:ItemIdentification"/>
            <corecomEBO:InventoryLocation>
               <xsl:copy-of select="ebo:SyncItemList/corecomEBO:InventoryLocation/corecom:Identification"/>
            </corecomEBO:InventoryLocation>
         </ebo:SyncItemListResponse>
      </ebo:DataArea>
   </xsl:template>
</xsl:stylesheet>
